name: Build
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game:"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # تنظیم نسخه جاوا (نسخه ۱۷ سازگارتر است)
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # نصب دستی Android SDK و NDK (حل مشکل ارور)
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Setup NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Build Module
      run: |
        chmod +x ./gradlew
        
        # ساخت فایل local.properties برای شناسایی SDK
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "ndk.dir=$ANDROID_NDK_HOME" >> local.properties
        
        # جایگزینی اسم پکیج
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
        
        # دستور بیلد
        ./gradlew :module:assembleRelease

    # آپلود فایل نهایی (نسخه جدید v4)
    - uses: actions/upload-artifact@v4
      with:
        name: zygisk-il2cppdumper
        path: out/magisk_module_release/
